In [12]:
import numpy as np

frequency = np.array([261.63, 293.66, 329.63, 349.23, 392, 440, 493])
# when  we do frequency.size we actually do np.ndarray.size



4


Что показывает атрибут ndarray.size?
Выберите один ответ:
Число измерений массива
Типы элементов массива
Форму массива
Количество элементов массива (x)


In [ ]:
print(np.array([1,2,3,4])[-1]) # here we print the index of the last element of the array so 4



In [17]:
print(np.array([1,2,3,4,5,6]).reshape(2, x))  #we are asked to change x by any number, if we change x by anything other than 3 we can't make the matrix

[[1 2 3]
 [4 5 6]]


In [20]:
frequency_one= np.array([261.63, 293.66, 329.63, 349.23, 392, 440, 493])
print(frequency_one.transpose())  # so taking the transpose is not doing anything, it will return the original matrix

[261.63 293.66 329.63 349.23 392.   440.   493.  ]


In [32]:
frequency_one= np.array([[261.63, 293.66, 329.63],[ 349.23, 392.0, 440.0]])   # if did 4 element in the second part it will give it a non-homogeneous shape
frequency_one[0,:] # to get the first line

# norm sum gives the distance between these two vectors


array([261.63, 293.66, 329.63])

In [40]:
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

#print(a[1,2]) so the index starts from zero, to and fro

# to get the dimension of the matrix can do

np.shape(a)
# or

a.shape

print(11 in a)  # we check if the element is in the matrix

False
