In [1]:
import numpy as np

In [2]:
#создание массива
datal = [ [5.2, 3.0, 4.5] , [9.1, 0.1, 0.3]]
arrl = np.array(datal) 
arrl

array([[5.2, 3. , 4.5],
       [9.1, 0.1, 0.3]])

In [3]:
arrl.ndim 

2

In [4]:
arrl.size

6

In [5]:
arrl.shape

(2, 3)

In [6]:
arrl.dtype

dtype('float64')

In [7]:
arrl.itemsize 

8

---

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [12]:
#единичная матрица
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Операции между массивами и скалярами

In [13]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) 

In [14]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [15]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

### Случайные массивы

In [17]:
np.random.randn(3,2)

array([[ 0.41307045,  0.21430778],
       [-1.19956569,  2.52518838],
       [-0.7469415 ,  0.57435652]])

In [18]:
np.random.randint(0, 1000, 4)

array([ 20, 785, 328, 804])

### Индексирование

Схоже с индексированием списков.

In [19]:
np.arange(15)[8:12]

array([ 8,  9, 10, 11])

In [20]:
#многомерные массивы
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [21]:
arr2d[0, 2] 

3

In [22]:
arr2d[0][2] 

3

In [23]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
arr3d[1,1][2]

12

In [24]:
arr3d[:1,:1,1:]

array([[[2, 3]]])

In [25]:
#булевое индексирование
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [26]:
mask = (names == 'Bob') | (names == 'Will') 
mask

array([ True, False,  True,  True,  True, False, False])

In [27]:
names[mask]

array(['Bob', 'Will', 'Bob', 'Will'], dtype='<U4')

### Транспонирование массивов

In [28]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr3d.shape

(2, 2, 3)

In [30]:
arr3d.T

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [31]:
arr3d.T.shape

(3, 2, 2)

### Поэлементные операции над массивами

Это векторные обертки вокруг простых функций, которые принимают одно или несколько скалярных значений и порождают один или несколько скалярных результатов.

In [32]:
np.sqrt(arr3d)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[2.64575131, 2.82842712, 3.        ],
        [3.16227766, 3.31662479, 3.46410162]]])

In [33]:
np.exp(arr3d)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]],

       [[1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
        [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]])

### Математические и статистические операции

In [34]:
arr = np.random.randn(5, 4) 
arr

array([[-0.74863261, -1.2787518 ,  0.48521841,  1.92351767],
       [-0.45501573, -0.87430218, -1.82198917, -2.05049957],
       [ 0.11371418,  0.21042436, -0.16792002, -2.06943752],
       [ 1.2612304 , -1.87745046,  1.24865131, -0.5006439 ],
       [-0.96431071, -0.29785692, -0.83051273, -0.92497898]])

In [35]:
arr.shape

(5, 4)

In [36]:
arr.mean()

-0.48097729862698424

In [37]:
arr.sum()

-9.619545972539685

In [38]:
np.max(arr)

1.9235176669889995

In [39]:
arr.sum(axis = 0)

array([-0.79301447, -4.117937  , -1.0865522 , -3.6220423 ])

In [40]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]) 

In [41]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [42]:
arr.cumprod(axis = 0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

### Сортировка

In [43]:
arr = np.random.randn(8) 
arr

array([-0.71680312,  0.10674762, -0.53476962,  0.51020456, -0.25568222,
        0.09255428, -0.44223847, -0.18400325])

In [44]:
arr.sort()
arr

array([-0.71680312, -0.53476962, -0.44223847, -0.25568222, -0.18400325,
        0.09255428,  0.10674762,  0.51020456])

In [45]:
arr = np.random.randn(5,3) 
arr

array([[ 0.8665742 ,  0.38534515, -2.15602239],
       [-0.2156394 ,  1.05004059, -1.86108003],
       [-0.59372003,  0.14104256,  0.54725326],
       [ 0.65729917, -1.02621462, -1.55362347],
       [ 0.10957587,  1.10748993, -1.48146344]])

In [46]:
arr.sort(0)
arr

array([[-0.59372003, -1.02621462, -2.15602239],
       [-0.2156394 ,  0.14104256, -1.86108003],
       [ 0.10957587,  0.38534515, -1.55362347],
       [ 0.65729917,  1.05004059, -1.48146344],
       [ 0.8665742 ,  1.10748993,  0.54725326]])

In [47]:
arr.sort(1) 
arr

array([[-2.15602239, -1.02621462, -0.59372003],
       [-1.86108003, -0.2156394 ,  0.14104256],
       [-1.55362347,  0.10957587,  0.38534515],
       [-1.48146344,  0.65729917,  1.05004059],
       [ 0.54725326,  0.8665742 ,  1.10748993]])

In [48]:
#возвращает копию
arr = np.random.randn(5,3) 
np.sort(arr)

array([[-2.18155234, -0.60561026,  0.58686431],
       [-1.37264772, -0.14011607,  1.09171741],
       [-0.55673431, -0.3052277 ,  0.40597668],
       [-1.95869758, -1.52114351,  0.35866463],
       [-1.0612078 , -0.29071306,  1.8410877 ]])

In [49]:
arr = np.sort(arr)
arr

array([[-2.18155234, -0.60561026,  0.58686431],
       [-1.37264772, -0.14011607,  1.09171741],
       [-0.55673431, -0.3052277 ,  0.40597668],
       [-1.95869758, -1.52114351,  0.35866463],
       [-1.0612078 , -0.29071306,  1.8410877 ]])

### Хранение массивов на диске в двоичном формате 

*np.save* и *np.load* - основные функции для эффективного сохранения и загрузки данных с диска. По умолчанию массивы хранятся в несжатом двоичном формате в файле с расширением *.npy*. 

In [50]:
arr = np.arange(10)

In [51]:
np.save('some_array', arr) 

In [52]:
np.load( 'some_array.npy') 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Можно сохранить несколько массивов в ziр-архиве с помощью функции np. savez, которой массивы передаются в виде именованных аргументов: 

In [53]:
np.savez('array_archive.npz', a=arr, b=arr) 

In [54]:
arch = np.load('array_archive.npz') 

In [55]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])